### ISSUE TITLE
New project imports break when `packages` in stack.yaml is not a list of strings

### ISSUE THREAD

**Issue by korayal** [carymrobbins/intellij-haskforce#221]
http://docs.haskellstack.org/en/stable/yaml_configuration.html?highlight=yaml#packages dictates that there is another alternative for `package` inside the yaml:

```
packages:
- some-directory
- https://example.com/foo/bar/baz-0.0.2.tar.gz
- location:
    git: git@github.com:commercialhaskell/stack.git
    commit: 6a86ee32e5b869a877151f74064572225e1a0398
- location:
    hg: https://example.com/hg/repo
    commit: da39a3ee5e6b4b0d3255bfef95601890afd80709
```
or
```
packages:
- local-package
- location: vendor/binary
  extra-dep: true
- location:
    git: git@github.com:yesodweb/wai
    commit: 2f8a8e1b771829f4a8a77c0111352ce45a14c30f
  subdirs:
  - auto-update
  - wai
```
instead of:

```
packages:
- dir1
- dir2
- dir3
```
