### ISSUE TITLE
Error:Could not parse stack.yaml: Expected YamlString, got: YamlAssoc [...]

### ISSUE THREAD

**Issue by runeksvendsen** [carymrobbins/intellij-haskforce#263]
The following stack.yaml file builds fine with stack, but in IntelliJ I get an error from HaskForce.

stack.yaml:

```
resolver: lts-5.2
packages:
- '.'
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: 7ccccb0a35ad959e4fcef91748c9d3653e39cb2e
  extra-dep: true
  subdirs:
    - haskoin-core
extra-deps:
- ed25519-0.0.5.0
- secp256k1-0.4.4
- spawn-0.3
- murmur3-1.0.1
- pbkdf-1.1.1.1
flags: {}
extra-package-dbs: []
```

IntelliJ error:

`Error:Could not parse /Users/rune/IdeaProjects/BitcoinClearingServer/stack.yaml: Expected YamlString, got: YamlAssoc(Map(location -> YamlAssoc(Map(git -> YamlString(https://github.com/haskoin/haskoin.git), commit -> YamlString(7ccccb0a35ad959e4fcef91748c9d3653e39cb2e))), extra-dep -> YamlBoolean(true), subdirs -> YamlList(List(YamlString(haskoin-core)))))`
